name: Build OpenWRT Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repo (pour récupérer .config)
        uses: actions/checkout@v3

      - name: Clone OpenWRT source v17.01.7
        run: git clone -b v17.01.7 https://git.openwrt.org/openwrt/openwrt.git

      - name: Installer dépendances
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-multilib libncurses5-dev zlib1g-dev gawk flex quilt libssl-dev xsltproc wget unzip python3

      - name: Copier .config dans le dossier openwrt
        run: cp .config openwrt/.config

      - name: Mettre à jour les feeds
        working-directory: openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Nettoyer la build
        working-directory: openwrt
        run: make clean

      - name: Compiler le firmware (mode verbeux)
        working-directory: openwrt
        run: |
          make defconfig
          make -j1 V=s
